skip-dirs-use-default: true

run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - errorlint
    - exportloopref
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosimple
    - gosec
    - govet
    - ineffassign
    - misspell
    - noctx
    - nolintlint
    - prealloc
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
  fast: true

linters-settings:
  goimports:
    local-prefixes: github.com/rjNemo/go-passgen